# Generated by Django 4.0.4 on 2022-05-27 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(max_length=12, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=None)),
                ('date_post', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
