# Generated by Django 4.0.4 on 2022-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_alter_artwork_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(default='no category', max_length=42),
        ),
        migrations.AddField(
            model_name='artwork',
            name='filter',
            field=models.CharField(default='no filter', max_length=42),
        ),
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(default='no title', max_length=42),
        ),
    ]
