# Generated by Django 4.0.4 on 2022-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_artwork_category_artwork_filter_artwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.CharField(default='No description yet.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(default='No category yet.', max_length=42),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='filter',
            field=models.CharField(default='No filter yet.', max_length=42),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(default='No title yet.', max_length=42),
        ),
    ]
