# Generated by Django 4.0.4 on 2022-06-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_artwork_description_alter_artwork_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='file',
            field=models.ImageField(upload_to='artworks/'),
        ),
    ]
