# Generated by Django 4.0.4 on 2022-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0006_alter_artwork_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='file',
            field=models.ImageField(upload_to='artworks_db/'),
        ),
    ]
