# Generated by Django 4.0.4 on 2022-06-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_alter_artwork_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='file',
            field=models.ImageField(upload_to='C:/newsfeed/artworks/'),
        ),
    ]
