# Generated by Django 4.0.4 on 2022-06-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0012_alter_artwork_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['id']},
        ),
    ]
