# Generated by Django 4.0.4 on 2022-06-03 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0013_alter_artwork_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDescriptionBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='code_description_blocks/')),
                ('parent_id', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['parent_id'],
            },
        ),
        migrations.CreateModel(
            name='CodeProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='No title yet.', max_length=42)),
                ('category', models.CharField(default='No category yet.', max_length=42)),
                ('file', models.ImageField(upload_to='code_projects/')),
                ('description', models.CharField(default='No description yet.', max_length=2000)),
                ('filter', models.CharField(default='No filter yet.', max_length=42)),
                ('date_post', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
