# Generated by Django 4.0.4 on 2022-06-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0014_codedescriptionblock_codeproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='full_file',
            field=models.ImageField(default=None, upload_to='artworks_full/'),
        ),
    ]
