"""
Django settings for florasora project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from pickle import FALSE

# for environment variables (security):
import environ

# Initialize environment variables:
env = environ.Env()

environ.Env.read_env()
#environ help: https://stackoverflow.com/questions/63137290/django-core-exceptions-improperlyconfigured-set-the-secret-key-environment-vari

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# What happens when you change your secret key: https://stackoverflow.com/questions/15170637/effects-of-changing-djangos-secret-key
# Getting a new secret key: https://stackoverflow.com/questions/41298963/is-there-a-function-for-generating-settings-secret-key-in-django
SECRET_KEY = env('SECRET_KEY')



# SECURITY WARNING: don't run with debug turned on in production!

debug_on        = 0
unsafe_hosts    = 0

if(debug_on):
    DEBUG = True
else:
    DEBUG = False

if(DEBUG):
    ALLOWED_HOSTS = []
else:
    if(unsafe_hosts):
        ALLOWED_HOSTS = ['*', env('MY_IP'), 'florasora.com']
    else:
        ALLOWED_HOSTS = [env('MY_IP'), 'florasora.com']



# Application definition

INSTALLED_APPS = [
	'newsfeed',
    'contact',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'florasora.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

            'libraries':{
            }
        },
    },
]

WSGI_APPLICATION = 'florasora.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASE_MY_USER = '******' #check .env
# DATABASE_DEFAULT_PASSWORD = '******' #check .env

DATABASES = {
	'default': {
    	'ENGINE': 'django.db.backends.mysql',
		'NAME': 'images',
		'USER': env('DATABASE_MY_USER'),
		'PASSWORD': env('DATABASE_DEFAULT_PASSWORD'),
		'HOST:': 'localhost',
		'PORT': env('DB_PORT'),
    		'OPTIONS': {
        		'read_default_file': '/etc/mysql/my.cnf',
	},
}
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Tijuana'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = 'static/'


if(DEBUG):
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'static'),
    )
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# reference: https://stackoverflow.com/questions/52452687/django-imagefield-will-not-display-on-webpage
# To allow django to serve images from database (which are stored in the actual project,
# as indicated by models.py in "upload_to" parameter):
MEDIA_ROOT = os.path.join(BASE_DIR, 'artworks_db')
MEDIA_URL = '/artworks_db/'

# only for development:
# DEBUG_PROPAGATE_EXCEPTIONS = True


# https://ordinarycoders.com/blog/article/build-a-django-contact-form-with-email-backend
# Email Support (added by coco):

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Youtube: how to support emails in django
# https://www.youtube.com/watch?v=xNqnHmXIuzU
# Medium: How to set up environmental variables in Django
# https://alicecampkin.medium.com/how-to-set-up-environment-variables-in-django-f3c4db78c55f
# How to send actual emails and not just console tests:
# https://data-flair.training/blogs/django-send-email/

# More email Support (for actual emails not justs tests):

EMAIL_HOST = 'smtp-mail.outlook.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = env('EMAIL_HOST_USER')  #check .env
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD') #check .env
EMAIL_USE_TLS = True
# EMAIL_USE_SSL = True


# Coco: pagination page links, for use by all views:
# https://docs.djangoproject.com/en/2.0/topics/settings/
GLOBAL_PAGE_TYPES = ["About Me", 
                    "Portfolio", 
                    "Contact",
                    "LinkedIn",
                    "Github",
                    ]


GLOBAL_PAGE_LINKS = ["/about_me/",
                    "/", 
                    "/contact/",
                    "https://www.linkedin.com/in/florasora/",
                    "https://github.com/CoreyWarren",
                    ]